### ISSUE TITLE
similar entries get subject confused

### ISSUE THREAD

**Issue by stas00** [mavam/gitdub#11]
It seems that there is a minor bug with matching entries with shared leading substring. I tried using this configuration:

```
  - id: fastai/fastai
    subject: '[fastai]'

  - id: fastai/fastai_docs
    subject: '[fastai_docs]'
```

And all emails were sent with the subject of the first entry. I found a workaround by flipping the order of the two entries, putting the longer one first, and now it works, but this is probably something that needs to be fixed ;)

Thank you.

**Comment by mavam** [comment]
Thanks for the bug report. I've pushed a potential fixed to master. Mind giving it a try?

**Comment by stas00** [comment]
Confirmed it to work. Thank you for the quick fix, @mavam.
